apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: login
spec:
  dnsNames:
    - argo.benz.in
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned