apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka
resources:
- strimzi-crds-0.40.0.yaml                
- strimzi-user-operator-0.40.0.yaml
- strimzi-cluster-operator-0.40.0.yaml    
- strimzi-topic-operator-0.40.0.yaml