apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres
resources:
- infrastructure-roles-new.yaml    
- minimal-postgres-manifest-12.yaml       
- ingress.yaml                            